# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82eb84d7e83e425737543942c3ae1c7595ad26c5b5693d3d17958b0042377275fec4a68ee8d565402e082f82abbb9d788392b509e926980d1c3ab6e293030df3

test:
  secret_key_base: 6d1e522659cd2b655bb588c5428c4aa911707685e88b7d1a21fa6b68fa24c03342df1e2dc81414ec3c08193bffa10a6daa860a173e204c74c9a7bfd63a4e0007

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
